### ISSUE TITLE
Default fluid temperatures

### ISSUE THREAD

**Issue by DaOneTrueCupcake** [shpaass/yafc-ce#214]
YAFC is trying to craft things with 200C water for some reason, and it would be great if I could tell it to always use 15C instead of modifying every recipe that uses water.

**Comment by shpaass** [comment]
Hi @DaOneTrueCupcake,
Could you please post the steps to reproduce the situation where Yafc prefers a 200C water of the 15C one?

**Comment by veger** [comment]
I notice the same with pY suite, since a while I suddenly are using 100C water instead of the 15C. I think we modified this behavior by accident...

We might need to do a bisect to figure when this started to happen, in order to see what this commit changed. I can do one this evening if no-one did this before I had the time.

**Comment by DaOneTrueCupcake** [comment]
I loaded YAFCCE with PyAE and selected all milestones. Further testing shows that it might just choose the highest accessable temperature; 100C is the default without chemical science selected, and 15C is the default with only automation science.
