### ISSUE TITLE
[Todo] Reproduce the warning in a nested table

### ISSUE THREAD

**Issue by shpaass** [shpaass/yafc-ce#268]
A link-related warning is located in `ProductionTableView#OpenProductDropdown#dropDownContent`. It reads as
> Nested tables have their own set of links that DON'T connect to parent links. To connect this product to the outside, remove this link.

This warning has the following trigger condition:
```
!link.flags.HasFlags(ProductionLink.Flags.HasProductionAndConsumption) &&
link.owner.owner is RecipeRow recipeRow && recipeRow.FindLink(link.goods, out _)
```
I reproduced this warning only once, randomly. After that, I failed to reproduce it. 

We need to understand what kind of confusion this warning aims to prevent and if this warning is triggered when expected.

**Comment by DaleStan** [comment]
It happens in this vanilla table, though it took me a while to realize you have to click on Iron plate to see the warning; just hovering doesn't do the trick.
```
inR0c+YKKMrPSk0uCUhMT+Uy0LPQM9Qz4OLiAgAAAP//5VRNa9wwEP0vOtsmTrrJ2seEBgLdspRcSslhZM16RWTJyFKSZdn/3uePXbbbtARySKE+jUbvvZl5GrwVlbOBbbjftCxK8R3QbOEUmwwEFaugnb0naVgkoo5aAaMupbyQ50x5cfVpVch5XsyvqOLZrJgV5/klkBqqorTRmERYanrlL9o+ZjdrbdRXFxYUqjUrIKfyotwKfmnJKmTL4CMnwoDRifLHVtTOKUTiLnCTtbrlNLi09i7aXoIaBFDIEZraeR3WjSjPdskJUXtn09ZQ4CPS2QnpIRGeK5QYK48xFL4Nwe/F0bsOGwA+D0FGXceNROt12lC11pbTC8BWkQ1AS/fMPmODh/C66om40i+sriOMAakbOhpStwNlRabjKXNna89KD3aN3g7p6aH2OQmpcKQ3Ztn2j3jwNlA9VGpANXxAdVH2k7X78xN5TTb0Xjz0fn6EHVn+TxhyvJ9TD39Y0Dft2ely9k6+by3/r2WEIb/Ad3+536I1YxYY3+M0DUExuFukl7SRVD1OoxrDHr8/8A4TMB39zMbTa4huyX4/qCjniXBP7L1WfONpFXA3otDNDt9P
```

**Comment by Dorus** [comment]
This is a mistake i've made many times while using YaFC. By now i know how links work, but it still bites me sometimes.

It's one of the things i have on my own private-mental-list of things to improve together with some other UI anoyances. (I know, i should probably write this all down in a concise way somewhere and not spread out of several issues like this). Anyway i think this is again one of the cases where the warning itself is good, but should be placed or accompanied with more visible indicators, like some coloring.

**Comment by shpaass** [comment]
> like some coloring

What kind of coloring were you thinking about? I just wanted to warn that more background colors to the links is bad unless we have a legend somewhere, because there's already overproduction that is not explicitly stated anywhere, so it will become a confusing situation if there are more unexplained colors.

**Comment by Dorus** [comment]
For "things linked elsewhere" it shouldn't be a too attention grabbing color, just something that indicate it is.

Other things i might want to indicate:
Some visual indication something...
- has a nested link that overrides an outer link.
- has a link elsewhere
- is linked (we have this)
- is connected to a link (we have this).
- is a duplicated recipe on the (same level/other level/other part of the sheet)
- is eligible to overproduce
- is overproducing
- is overproducing and linked (we have this)
- is ingredient
- is not the lowest temperature fluid input

Possibly it's too much to do all of this with just plain background colors. We might need some other UI solution like borders. For the few about duplicate recipes: This can color the recipe icon instead of the ingredients/products.

I agree all possibly addition of more colors should come hand in hand with some legend or tip etc.

**Comment by shpaass** [comment]
Regarding the original issue of reproducing the warning, it turned out that the warning is reproducible, and the visibility of warnings was improved in https://github.com/shpaass/yafc-ce/pull/279
