### ISSUE TITLE
YAFC crashes on creating project with Kux-BlueprintExtensions mod

### ISSUE THREAD

**Issue by Martmists-GH** [shpaass/yafc-ce#346]
```lua
Unhandled exception. Yafc.Parser.LuaException: (Kux-CoreLib, lib/ModInfo.lua):136: attempt to concatenate field 'version' (a nil value)
stack traceback:
[C]: in function '__concat'
(Kux-CoreLib, lib/ModInfo.lua):136: in function 'update'
(Kux-CoreLib, lib/ModInfo.lua):145: in main chunk
[C]: in function 'require'
(Kux-CoreLib, lib/init.lua):179: in function '__index'
(Kux-BlueprintExtensions, mod.lua):4: in main chunk
[C]: in function 'require'
(Kux-BlueprintExtensions, data.lua):1: in main chunk
   at Yafc.Parser.LuaContext.Exec(ReadOnlySpan`1 chunk, String mod, String name, Int32 argument) in ./Yafc.Parser/LuaContext.cs:line 499
   at Yafc.Parser.LuaContext.Require(IntPtr lua) in ./Yafc.Parser/LuaContext.cs:line 441
/usr/bin/factorio-yafc-ce: line 3: 330607 Aborted                 (core dumped) dotnet --roll-forward Major /usr/lib/factorio-yafc-ce-git/Yafc.dll "$@"
```

YAFC version: 2.1.0.38.g31c9906
OS: Arch Linux x64
Installation method: [AUR](https://aur.archlinux.org/packages/factorio-yafc-ce-git)

**Comment by DaleStan** [comment]
There should be a "Disable & reload" button on that error dialog. Please click it to disable Kux-BlueprintExtensions and load the rest of your mods.

![image](https://github.com/user-attachments/assets/a255fd6f-ab5a-40ba-9a87-4f914afaf700)

**Comment by Martmists-GH** [comment]
There is no dialog, the app just crashes immediately.

**Comment by DaleStan** [comment]
The other workaround is to create a copy of your mods/ directory, edit the copied mod-list.json to disable Kux-CoreLib, and then tell Yafc to use that directory instead of the real one.
I don't know why your system isn't giving you an error message, but I'd see if the package maintainer has any ideas. (Or maybe the dialog just doesn't work on Linux? That would be unfortunate.)

The actual fix is either https://github.com/kuxynator/Kux-BlueprintExtensions/issues/4 or someone with lots of Lua source and/or Lua C API knowledge updating things so Yafc-CE follows Factorio's lead of allowing concatenation with nil.

**Comment by veger** [comment]
> Or maybe the dialog just doesn't work on Linux?

I tried by installing the mod, and it is indeed not showing, I'll create a issue to fix this.
